services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hivek-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REDIS_HOST=redis
      # - NODE_ENV=production
    deploy:
          resources:
            limits:
              cpus: '4.0'    # Chỉ cho phép NestJS dùng tối đa 1 Core CPU
              memory: 1G  # Chỉ cho phép dùng tối đa 512MB RAM
    restart: none

networks:
  default:
    name: hivek-network
