export enum EFailureType {
	NETWORK = 'NETWORK',
	AUTHENTICATION = 'AUTHENTICATION',
	VALIDATION = 'VALIDATION',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	FRAUD_DETECTED = 'FRAUD_DETECTED',
	TIMEOUT = 'TIMEOUT',
	UNKNOWN = 'UNKNOWN',
}
