export enum EPaymentEventType {
	// Payment Events
	PAYMENT_CREATED = 'PAYMENT_CREATED',
	PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
	PAYMENT_FAILED = 'PAYMENT_FAILED',
	PAYMENT_CANCELED = 'PAYMENT_CANCELED',
	PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
	PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
	PAYMENT_RETRY = 'PAYMENT_RETRY',

	// Refund Events
	REFUND_INITIATED = 'REFUND_INITIATED',
	REFUND_SUCCEEDED = 'REFUND_SUCCEEDED',
	REFUND_FAILED = 'REFUND_FAILED',

	PARTIAL_REFUND_INITIATED = 'PARTIAL_REFUND_INITIATED',
	PARTIAL_REFUND_SUCCEEDED = 'PARTIAL_REFUND_SUCCEEDED',
	PARTIAL_REFUND_FAILED = 'PARTIAL_REFUND_FAILED',

	// Attempt Events
	ATTEMPT_INITIATED = 'ATTEMPT_INITIATED',
	ATTEMPT_SUCCEEDED = 'ATTEMPT_SUCCEEDED',
	ATTEMPT_FAILED = 'ATTEMPT_FAILED',
	ATTEMPT_CANCELED = 'ATTEMPT_CANCELED',

	WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
}
