export enum EPaymentStatus {
	PENDING_PAYMENT_PROVIDER = 'PENDING_PAYMENT_PROVIDER',
	PENDING = 'PENDING',
	PROCESSING = 'PROCESSING',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
	REFUNDED = 'REFUNDED',
	CANCELED = 'CANCELED',
}
