export enum EPaymentAttemptStatus {
	INITIATED = 'INITIATED',
	PROCESSING = 'PROCESSING',
	SUCCESS = 'SUCCESS',
	FAILED = 'FAILED',
	CANCELED = 'CANCELED',
	PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
	REFUNDED = 'REFUNDED',
}
